language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
env:
  matrix:
    - RAILS_VERSION=5.0.5
    - RAILS_VERSION=5.1.6
    - RAILS_VERSION=5.2.0
before_install:
  - gem update bundler
  - bundle update
