language: ruby
cache: bundler
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0
env:
  matrix:
    - RAILS_VERSION=5.0.5
    - RAILS_VERSION=5.1.0
    - RAILS_VERSION=5.1.1
    - RAILS_VERSION=5.1.2
    - RAILS_VERSION=5.1.3
    - RAILS_VERSION=5.1.4
before_install:
  - gem update bundler
  - bundle update
